# Python

In [1]:
import numpy as np
import pandas as pd
from decimal import Decimal
from euclide import pgcd

In [2]:
m = np.random.normal(10,3,(100,100))
m

array([[ 9.24103401, 12.3464509 ,  8.07960333, ...,  5.45773496,
        11.24499147,  8.55297912],
       [ 9.82706718,  9.1114973 , 11.22745192, ..., 14.26069434,
        11.02367197,  9.44253435],
       [ 9.79631796, 13.85960752, 13.45085926, ...,  9.8189424 ,
        10.64898102,  8.88026183],
       ...,
       [10.89889748,  6.95249572, 15.248387  , ..., 10.10446869,
        12.91100474,  7.19384491],
       [ 2.82426014,  7.79429798,  9.64310678, ..., 13.64071645,
         4.40876592,  9.54457004],
       [ 8.7972775 ,  7.5806462 , 14.30077701, ..., 10.79968645,
         7.71744508, 12.6162679 ]])

In [3]:
# attribute: tuple
m.shape

(100, 100)

In [4]:
m.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [5]:
# TypeError: 'numpy.flagsobj' object is not callable
# m.flags()

In [6]:
m.sum

<function ndarray.sum>

In [7]:
m.sum()

100502.3941373472

In [8]:
m

array([[ 9.24103401, 12.3464509 ,  8.07960333, ...,  5.45773496,
        11.24499147,  8.55297912],
       [ 9.82706718,  9.1114973 , 11.22745192, ..., 14.26069434,
        11.02367197,  9.44253435],
       [ 9.79631796, 13.85960752, 13.45085926, ...,  9.8189424 ,
        10.64898102,  8.88026183],
       ...,
       [10.89889748,  6.95249572, 15.248387  , ..., 10.10446869,
        12.91100474,  7.19384491],
       [ 2.82426014,  7.79429798,  9.64310678, ..., 13.64071645,
         4.40876592,  9.54457004],
       [ 8.7972775 ,  7.5806462 , 14.30077701, ..., 10.79968645,
         7.71744508, 12.6162679 ]])

In [9]:
x = 123444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444447

In [10]:
x + 1

123444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444448

In [11]:
type(x)

int

### Types entiers de numpy vs type int de python
- uint8: unsigned int sur 8 bits, i.e. 0 à 255
- int8: signed int sur 8 bits; i.e. -128 à 127
- int8, int16, int32, int64
- uint8, uint16, uint32, uint64

In [12]:
m = np.ones((5,5), dtype=np.uint8)
m

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [13]:
print(m)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Types flottants (IEEE754)
- python: float, 32/64 en fonction de la machine
- numpy: float32, float64

In [14]:
prix = 0.10
prix, 2*prix, 3*prix

(0.1, 0.2, 0.30000000000000004)

In [15]:
prix = Decimal('0.1')
prix, 2*prix, 3*prix

(Decimal('0.1'), Decimal('0.2'), Decimal('0.3'))

In [16]:
np.nan, np.inf, float('nan'), float('inf')

(nan, inf, nan, inf)

bigNumber = 1E308
bigNumber, bigNumber*2

### Calculs

In [17]:
r1, r2, r3 = 11 / 3, 11 // 3, 11 % 3
print(r1, r2, r3)

3.6666666666666665 3 2


In [18]:
2**10

1024

### Logique
- True, False
- comparaison: ==, !=, <, <=, >, >=
- and, or, not

In [19]:
(r1 > 5) and (r3 == 2)

False

In [20]:
'5' == 5

False

In [21]:
# TypeError: '<=' not supported between instances of 'str' and 'int'
# '5' <= 5

In [22]:
None, type(None)

(None, NoneType)

In [23]:
x = None
x is None, x is not None

(True, False)

In [24]:
3 in [45, 3, 77], 3 not in [45, 3, 77]

(True, False)

In [25]:
l1 = [3, 4, 5]
l2 = [3, 4, 5]
## == contenu, is mémoire
l1 == l2, l1 is l2, l1 is not l2

(True, False, True)

### Textes

In [26]:
data = 'Tou"lou\'se', "Tou'lou\"se", '''Toulouse''', """Toulouse"""
data

('Tou"lou\'se', 'Tou\'lou"se', 'Toulouse', 'Toulouse')

In [27]:
for ville in data:
    print(ville)

Tou"lou'se
Tou'lou"se
Toulouse
Toulouse


In [28]:
sql = """SELECT
    nom, pop
FROM villes
WHERE dep = 31"""
print(sql)

SELECT
    nom, pop
FROM villes
WHERE dep = 31


In [29]:
ville = "Toulouse"

In [30]:
ville + ", ville rose"

'Toulouse, ville rose'

In [31]:
# TypeError: can only concatenate str (not "int") to str
# ville + 5

In [32]:
pop = 400000
densite = 33.44559977

In [33]:
# formatted string de python 3.6
f"{ville} a une population de {pop}, avec une densité de {densite}"

'Toulouse a une population de 400000, avec une densité de 33.44559977'

In [34]:
f"{ville} a une population de {pop}, avec une densité de {densite:0.2f}"

'Toulouse a une population de 400000, avec une densité de 33.45'

In [35]:
# python 3
print("{} a une population de {}, avec une densité de {:0.2f}".format(ville, pop, densite))
print("{0} a une population de {1}, avec une densité de {2:0.2f}".format(ville, pop, densite))

Toulouse a une population de 400000, avec une densité de 33.45
Toulouse a une population de 400000, avec une densité de 33.45


In [36]:
# python 1,2 old school
"%s a une population de %s, avec une densité de %s" % (ville, pop, densite)

'Toulouse a une population de 400000, avec une densité de 33.44559977'

In [37]:
recap = [3, 3.3, Decimal('3.3'), 'Toulouse']
for d in recap:
    print(d, type(d))

3 <class 'int'>
3.3 <class 'float'>
3.3 <class 'decimal.Decimal'>
Toulouse <class 'str'>


In [38]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [39]:
range?

Init signature: range(self, /, *args, **kwargs)
Docstring:     
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).
Type:           type
Subclasses:     


In [40]:
# range is a lazy object since python 3
range(1,10,2)

range(1, 10, 2)

In [41]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [42]:
# builtin function sum (from python)
sum(m)

array([5, 5, 5, 5, 5], dtype=uint8)

In [43]:
# function sum from numpy
np.sum(m)

25

In [44]:
# function sum from object m (class ndarray)
m.sum()

25

## Numpy (intro)
https://numpy.org/doc/stable/reference/routines.array-creation.html

In [45]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m1              

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
v2 = np.zeros(10)
v2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
m3 = np.ones((5,5))
m3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
m4 = np.full((5,5), 2)
m4

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [49]:
np.pi

3.141592653589793

In [50]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that pas

In [51]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [52]:
dir(m1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [53]:
print(len(m1)) # call m1.__len__()
print(str(m1)) # i.e print(m1), call m1.__str__()
print(repr(m1)) # call m1.__repr__()

3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


### Sequences: list, tuple, set

In [54]:
villes = [ "Toulouse", "Pau", "Lille" ]  # modifiable, "homogene"
ville = ("Toulouse", 400000, '31000') # non modifiable, "heterogene"
nombreSet = { 1, 2, 3, 2, 7 } # modifiable

In [55]:
nombreSet

{1, 2, 3, 7}

In [56]:
for v in villes:
    print(v)
for d in ville:
    print(d)
for v in nombreSet:
    print(v)    

Toulouse
Pau
Lille
Toulouse
400000
31000
1
2
3
7


In [57]:
# objets iterable
it = iter(villes) # call villes.__iter__

In [58]:
iter(it) is it

True

In [59]:
# set is iterable
sum(nombreSet)

13

In [60]:
# renvoie la valeur suivante jusqu'à exception StopIteration
it = iter(villes)
while True:
    try: 
        v = next(it)
        print(v)
    except StopIteration:
        break # sort de la boucle

Toulouse
Pau
Lille


In [61]:
for i, v in enumerate(villes):
    print('-',i,v)
for i, v in enumerate(villes, 1):
    print('*',i,v)

- 0 Toulouse
- 1 Pau
- 2 Lille
* 1 Toulouse
* 2 Pau
* 3 Lille


In [62]:
for v, n, d in zip(villes, nombreSet, ville):
    print(n, v, d)

1 Toulouse Toulouse
2 Pau 400000
3 Lille 31000


In [63]:
res = []
for n in nombreSet:
    res.append(n**2+1)
res

[2, 5, 10, 50]

In [64]:
# list comprehension
res = [ n**2+1 for n in nombreSet ]
res

[2, 5, 10, 50]

In [65]:
res = list(map(lambda n: n**2+1, nombreSet))  # map is lazy
res

[2, 5, 10, 50]

In [66]:
# expression for: generator
g = (n**2+1 for n in nombreSet)
g

<generator object <genexpr> at 0x000001BA1F088AC0>

In [67]:
sum(n**2+1 for n in nombreSet)

67

In [68]:
sum((n**2+1 for n in nombreSet), 100)

167

In [69]:
villeDict = { 'nom': 'Toulouse', 'pop': 400000, 'cp': '31000'}
villeDict

{'nom': 'Toulouse', 'pop': 400000, 'cp': '31000'}

In [70]:
print(villeDict['pop'])
villeDict['pop'] = 500000
print(villeDict['pop'])
villeDict['pop'] += 50000
print(villeDict['pop'])

400000
500000
550000


In [71]:
villeDict['maire'] = 'Super maire'
print(villeDict)
del villeDict['maire']
print(villeDict)

{'nom': 'Toulouse', 'pop': 550000, 'cp': '31000', 'maire': 'Super maire'}
{'nom': 'Toulouse', 'pop': 550000, 'cp': '31000'}


In [72]:
for x in villeDict:  # iter on keys
    print(x)

nom
pop
cp


In [73]:
# 3 iterateurs: items, values, keys
for k, v in villeDict.items():
    print(k,v)

nom Toulouse
pop 550000
cp 31000


In [74]:
# dict comprehension (attention pas de doublons de clés)
{ v: len(v) for v in villes }

{'Toulouse': 8, 'Pau': 3, 'Lille': 5}

In [75]:
x = 10
if x < 20:
    pass
elif x < 30:
    pass
else:
    pass


In [76]:
'OK' if x < 10 else 'KO'

'KO'

In [77]:
[ 'KO' if x < 10 else ('BOF' if x < 20 else 'OK') for x in [2, 12, 25]]

['KO', 'BOF', 'OK']

In [78]:
for a, _, c in ((1,2,3), (4,5,6), (7,8,9)):
    print(a,c)

1 3
4 6
7 9


In [79]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    sep=<no_default>,
    delimiter=None,
    header='infer',
    names=<no_default>,
    index_col=None,
    usecols=None,
    squeeze=None,
    prefix=<no_default>,
    mangle_dupe_cols=True,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace=False,
    skiprows=None,
    skipfooter=0,
    nrows=None,
    na_values=None,
    keep_default_na=True,
    na_filter=True,
    verbose=False,
    skip_blank_lines=True,
    parse_dates=None,
    infer_datetime_format=False,
    keep_date_col=False,
    date_parser=None,
    dayfirst=False,
    cache_dates=True,
    iterator=False,
    chunksize=None,
    compression: 'CompressionOptions' = 'infer',
    thousands=None,
    decimal: 'str' = '.',
    lineterminator=None,
    quotechar='"',
    quoting=0,
    doublequote=True,
    esc

### Operator [] and Slices

In [80]:
villeStr = "Toulouse"

In [81]:
print(villeStr[0])
print(villeStr[7])
print(villeStr[-1])  # len(villeStr) -1
print(villeStr[-8])

T
e
e
T


In [82]:
print(villes)
print(villes[0])
print(villes[-1])

['Toulouse', 'Pau', 'Lille']
Toulouse
Lille


In [83]:
# IndexError: list index out of range
# villes[3]

In [84]:
# KeyError: 'cinema'
# villeDict['cinema']
'cinema' in villeDict

False

In [85]:
# extension aux tuples pour les ndarray
print(m1[1,2])
print(m1[-1,-1])

6
9


In [86]:
# slice 1:3, i.e. from index 1 (included), to index 3 (excluded) 
print(villeStr, villeStr[1:3]) 
print(villeStr, villeStr[:3])   # until index 3 (excluded)
print(villeStr, villeStr[3:])   # from index 3 to the end
print(villeStr, villeStr[-3:])  # 3 last ones

Toulouse ou
Toulouse Tou
Toulouse louse
Toulouse use


In [87]:
m1[:2, :2]

array([[1, 2],
       [4, 5]])

In [88]:
m1[slice(0,2), slice(0,2)]

array([[1, 2],
       [4, 5]])

In [89]:
m1[slice(None,2), slice(-2,None)]  # m1[:2, -2:]

array([[2, 3],
       [5, 6]])

In [90]:
print(villeStr[::2])  # even indexes (pair)
print(villeStr[1::2]) # odd indexes (impair)
print(villeStr[::-1]) # reverse

Tuos
olue
esuoluoT


In [91]:
m1[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [92]:
m1.T  # is a view

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [93]:
print(villeStr[15:])
print(villes[15:])
print(m1[15:, 15:])


[]
[]


In [94]:
m1[0,0] = 111
m1

array([[111,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [95]:
# str is not mutable
# TypeError: 'str' object does not support item assignment
# villeStr[0] = 'Y'

In [96]:
print(villes)
villes[1] = 'Bayonne'
print(villes)

['Toulouse', 'Pau', 'Lille']
['Toulouse', 'Bayonne', 'Lille']


In [97]:
m1[-2:, -2:] = ((55, 66), (88, 99))
m1

array([[111,   2,   3],
       [  4,  55,  66],
       [  7,  88,  99]])

In [98]:
m1[-2:, -2:] = 1234
m1

array([[ 111,    2,    3],
       [   4, 1234, 1234],
       [   7, 1234, 1234]])

In [99]:
# remplacer les 2 dernières valeurs par 3 nouvelles
villes[-2:] = ['Pau', 'Blagnac', 'Balma']
villes

['Toulouse', 'Pau', 'Blagnac', 'Balma']

### Utilisation fonctions custom

In [100]:
pgcd(34,51)

17

In [101]:
pgcd?

Signature: pgcd(a: int, b: int) -> int
Docstring:
plus grand commun diviseur de 2entiers naturels 
strictement positifs
File:      c:\users\matthias\documents\formations\python\ds202210\euclide.py
Type:      function


In [102]:
help(pgcd)

Help on function pgcd in module euclide:

pgcd(a: int, b: int) -> int
    plus grand commun diviseur de 2entiers naturels 
    strictement positifs



In [103]:
# pgcd('toto', 'titi') # appel non refusé => use a type checker
# TypeError: not all arguments converted during string formatting