# Python

In [18]:
import numpy as np
import pandas as pd
from decimal import Decimal

In [2]:
m = np.random.normal(10,3,(100,100))
m

array([[14.69071037, 14.90207985,  8.29036612, ..., 11.48700386,
         8.33164039,  7.8969637 ],
       [15.65388296, 15.02464453, 10.62842504, ..., 13.24377979,
        10.72566701,  8.89400752],
       [14.61406694, 10.97381834, 11.65587622, ...,  3.74591376,
         9.75997291,  9.20582171],
       ...,
       [11.17397579,  3.97304654, 11.30562006, ...,  8.40112901,
         5.38730178,  9.58505939],
       [ 5.84463737,  4.08114869, 10.02710942, ..., 11.58817669,
         1.76431535, 12.13647076],
       [ 8.74817476,  3.47372789,  9.87709503, ...,  6.11509696,
         9.52470281,  9.64955499]])

In [3]:
# attribute: tuple
m.shape

(100, 100)

In [4]:
m.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [5]:
# TypeError: 'numpy.flagsobj' object is not callable
# m.flags()

In [6]:
m.sum

<function ndarray.sum>

In [7]:
m.sum()

99893.85063753751

In [8]:
m

array([[14.69071037, 14.90207985,  8.29036612, ..., 11.48700386,
         8.33164039,  7.8969637 ],
       [15.65388296, 15.02464453, 10.62842504, ..., 13.24377979,
        10.72566701,  8.89400752],
       [14.61406694, 10.97381834, 11.65587622, ...,  3.74591376,
         9.75997291,  9.20582171],
       ...,
       [11.17397579,  3.97304654, 11.30562006, ...,  8.40112901,
         5.38730178,  9.58505939],
       [ 5.84463737,  4.08114869, 10.02710942, ..., 11.58817669,
         1.76431535, 12.13647076],
       [ 8.74817476,  3.47372789,  9.87709503, ...,  6.11509696,
         9.52470281,  9.64955499]])

In [9]:
x = 123444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444447

In [10]:
x + 1

123444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444448

In [11]:
type(x)

int

### Types entiers de numpy vs type int de python
- uint8: unsigned int sur 8 bits, i.e. 0 à 255
- int8: signed int sur 8 bits; i.e. -128 à 127
- int8, int16, int32, int64
- uint8, uint16, uint32, uint64

In [14]:
m = np.ones((5,5), dtype=np.uint8)
m

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [15]:
print(m)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Types flottants (IEEE754)
- python: float, 32/64 en fonction de la machine
- numpy: float32, float64

In [16]:
prix = 0.10
prix, 2*prix, 3*prix

(0.1, 0.2, 0.30000000000000004)

In [19]:
prix = Decimal('0.1')
prix, 2*prix, 3*prix

(Decimal('0.1'), Decimal('0.2'), Decimal('0.3'))

In [21]:
np.nan, np.inf, float('nan'), float('inf')

(nan, inf, nan, inf)

bigNumber = 1E308
bigNumber, bigNumber*2

### Calculs

In [29]:
r1, r2, r3 = 11 / 3, 11 // 3, 11 % 3
print(r1, r2, r3)

3.6666666666666665 3 2


In [27]:
2**10

1024

### Logique
- True, False
- comparaison: ==, !=, <, <=, >, >=
- and, or, not

In [30]:
(r1 > 5) and (r3 == 2)

False

In [31]:
'5' == 5

False

In [33]:
# TypeError: '<=' not supported between instances of 'str' and 'int'
# '5' <= 5

In [34]:
None, type(None)

(None, NoneType)

In [35]:
x = None
x is None, x is not None

(True, False)

In [39]:
3 in [45, 3, 77], 3 not in [45, 3, 77]

(True, False)

In [40]:
l1 = [3, 4, 5]
l2 = [3, 4, 5]
## == contenu, is mémoire
l1 == l2, l1 is l2, l1 is not l2

(True, False, True)

### Textes

In [43]:
data = 'Tou"lou\'se', "Tou'lou\"se", '''Toulouse''', """Toulouse"""
data

('Tou"lou\'se', 'Tou\'lou"se', 'Toulouse', 'Toulouse')

In [47]:
for ville in data:
    print(ville)

Tou"lou'se
Tou'lou"se
Toulouse
Toulouse


In [45]:
sql = """SELECT
    nom, pop
FROM villes
WHERE dep = 31"""
print(sql)

SELECT
    nom, pop
FROM villes
WHERE dep = 31


In [48]:
ville = "Toulouse"

In [49]:
ville + ", ville rose"

'Toulouse, ville rose'

In [51]:
# TypeError: can only concatenate str (not "int") to str
# ville + 5

In [55]:
pop = 400000
densite = 33.44559977

In [59]:
# formatted string de python 3.6
f"{ville} a une population de {pop}, avec une densité de {densite}"

'Toulouse a une population de 400000, avec une densité de 33.44559977'

In [58]:
f"{ville} a une population de {pop}, avec une densité de {densite:0.2f}"

'Toulouse a une population de 400000, avec une densité de 33.45'

In [63]:
# python 3
print("{} a une population de {}, avec une densité de {:0.2f}".format(ville, pop, densite))
print("{0} a une population de {1}, avec une densité de {2:0.2f}".format(ville, pop, densite))

Toulouse a une population de 400000, avec une densité de 33.45
Toulouse a une population de 400000, avec une densité de 33.45


In [66]:
# python 1,2 old school
"%s a une population de %s, avec une densité de %s" % (ville, pop, densite)

'Toulouse a une population de 400000, avec une densité de 33.44559977'